// <auto-generated />
using System;
using Clientes.Persistencias;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMorfar.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241002034532_uml v1")]
    partial class umlv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Comanda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("apellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Comandaid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("Comandaid");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ComandaPersona", b =>
                {
                    b.Property<int>("comandasid")
                        .HasColumnType("int");

                    b.Property<int>("personasid")
                        .HasColumnType("int");

                    b.HasKey("comandasid", "personasid");

                    b.HasIndex("personasid");

                    b.ToTable("ComandaPersona");
                });

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Producto", b =>
                {
                    b.HasOne("AMorfar.Negocios.Entidades.Comanda", null)
                        .WithMany("productos")
                        .HasForeignKey("Comandaid");
                });

            modelBuilder.Entity("ComandaPersona", b =>
                {
                    b.HasOne("AMorfar.Negocios.Entidades.Comanda", null)
                        .WithMany()
                        .HasForeignKey("comandasid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMorfar.Negocios.Entidades.Persona", null)
                        .WithMany()
                        .HasForeignKey("personasid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Comanda", b =>
                {
                    b.Navigation("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
