// <auto-generated />
using System;
using Clientes.Persistencias;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMorfar.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241003233736_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Comanda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Persona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("ComandaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ComandaID");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ComandaPersona", b =>
                {
                    b.Property<int>("ComandasID")
                        .HasColumnType("int");

                    b.Property<int>("PersonasID")
                        .HasColumnType("int");

                    b.HasKey("ComandasID", "PersonasID");

                    b.HasIndex("PersonasID");

                    b.ToTable("ComandaPersona");
                });

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Producto", b =>
                {
                    b.HasOne("AMorfar.Negocios.Entidades.Comanda", null)
                        .WithMany("Productos")
                        .HasForeignKey("ComandaID");
                });

            modelBuilder.Entity("ComandaPersona", b =>
                {
                    b.HasOne("AMorfar.Negocios.Entidades.Comanda", null)
                        .WithMany()
                        .HasForeignKey("ComandasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMorfar.Negocios.Entidades.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMorfar.Negocios.Entidades.Comanda", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
